/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The board model.
 *
 */
class BoardModel {
  /**
   * Create a BoardModel.
   * @member {number} [boardId] Gets or sets the board identifier.
   * @member {number} [accountId] Gets or sets the account identifier.
   * @member {number} [createdUserId] Gets or sets the created user identifier.
   * @member {number} [modifiedUserId] Gets or sets the modified user
   * identifier.
   * @member {string} [name] Gets or sets the name.
   * @member {string} [description] Gets or sets the description.
   * @member {date} [createdDate] Gets or sets the created date.
   * @member {date} [modifiedDate] Gets or sets the modified date.
   */
  constructor() {
  }

  /**
   * Defines the metadata of BoardModel
   *
   * @returns {object} metadata of BoardModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BoardModel',
      type: {
        name: 'Composite',
        className: 'BoardModel',
        modelProperties: {
          boardId: {
            required: false,
            nullable: false,
            serializedName: 'boardId',
            type: {
              name: 'Number'
            }
          },
          accountId: {
            required: false,
            nullable: false,
            serializedName: 'accountId',
            type: {
              name: 'Number'
            }
          },
          createdUserId: {
            required: false,
            nullable: false,
            serializedName: 'createdUserId',
            type: {
              name: 'Number'
            }
          },
          modifiedUserId: {
            required: false,
            nullable: false,
            serializedName: 'modifiedUserId',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          createdDate: {
            required: false,
            nullable: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          modifiedDate: {
            required: false,
            nullable: false,
            serializedName: 'modifiedDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = BoardModel;
