/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the BoardModel class.
 * @constructor
 * The board model.
 *
 * @member {number} [boardId] Gets or sets the board identifier.
 * @member {number} [accountId] Gets or sets the account identifier.
 * @member {number} [createdUserId] Gets or sets the created user identifier.
 * @member {number} [modifiedUserId] Gets or sets the modified user identifier.
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 * @member {date} [createdDate] Gets or sets the created date.
 * @member {date} [modifiedDate] Gets or sets the modified date.
 */
export interface BoardModel {
  boardId?: number;
  accountId?: number;
  createdUserId?: number;
  modifiedUserId?: number;
  name?: string;
  description?: string;
  createdDate?: Date;
  modifiedDate?: Date;
}

/**
 * @class
 * Initializes a new instance of the BoardPutModel class.
 * @constructor
 * The board put model.
 *
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 */
export interface BoardPutModel {
  name?: string;
  description?: string;
}

/**
 * @class
 * Initializes a new instance of the BoardPostModel class.
 * @constructor
 * The board post model.
 *
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 */
export interface BoardPostModel {
  name?: string;
  description?: string;
}

/**
 * @class
 * Initializes a new instance of the BoardHistoryModel class.
 * @constructor
 * The Board History Model.
 *
 * @member {number} [boardHistoryId] Gets or sets the board history identifier.
 * @member {number} [boardId] Gets or sets the board identifier.
 * @member {number} [accountId] Gets or sets the account identifier.
 * @member {number} [createdUserId] Gets or sets the created user identifier.
 * @member {number} [modifiedUserId] Gets or sets the modified user identifier.
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 * @member {date} [createdDate] Gets or sets the created date.
 * @member {date} [modifiedDate] Gets or sets the modified date.
 */
export interface BoardHistoryModel {
  boardHistoryId?: number;
  boardId?: number;
  accountId?: number;
  createdUserId?: number;
  modifiedUserId?: number;
  name?: string;
  description?: string;
  createdDate?: Date;
  modifiedDate?: Date;
}

/**
 * @class
 * Initializes a new instance of the BoardFilterModel class.
 * @constructor
 * The Board Get Request Model.
 *
 * @member {string} [name] Gets or sets the name.
 * @member {date} [createdDate] Gets or sets the created date.
 * @member {date} [modifiedDate] Gets or sets the modified date.
 */
export interface BoardFilterModel {
  name?: string;
  createdDate?: Date;
  modifiedDate?: Date;
}

/**
 * @class
 * Initializes a new instance of the SwitchModel class.
 * @constructor
 * Switch Model.
 *
 * @member {number} [switchId] Gets or sets the switch identifier.
 * @member {number} [boardId] Gets or sets the board identifier.
 * @member {number} [createdUserId] Gets or sets the created user identifier.
 * @member {number} [modifiedUserId] Gets or sets the modified user identifier.
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 * @member {string} [comment] Gets or sets the comment.
 * @member {date} [createdDate] Gets or sets the created date.
 * @member {date} [modifiedDate] Gets or sets the modified date.
 * @member {string} [value] Gets or sets the value.
 * @member {string} [valueType] Gets or sets the type of the value.
 * @member {string} [version] Gets or sets the version.
 */
export interface SwitchModel {
  switchId?: number;
  boardId?: number;
  createdUserId?: number;
  modifiedUserId?: number;
  name?: string;
  description?: string;
  comment?: string;
  createdDate?: Date;
  modifiedDate?: Date;
  value?: string;
  valueType?: string;
  version?: string;
}

/**
 * @class
 * Initializes a new instance of the SwitchPostModel class.
 * @constructor
 * Switch Post Model.
 *
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 * @member {string} [comment] Gets or sets the comment.
 * @member {string} [value] Gets or sets the value.
 * @member {string} [valueType] Gets or sets the type of the value.
 */
export interface SwitchPostModel {
  name?: string;
  description?: string;
  comment?: string;
  value?: string;
  valueType?: string;
}

/**
 * @class
 * Initializes a new instance of the SwitchPutModel class.
 * @constructor
 * Switch Put Model.
 *
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 * @member {string} [comment] Gets or sets the comment.
 * @member {string} [value] Gets or sets the value.
 * @member {string} [valueType] Gets or sets the type of the value.
 */
export interface SwitchPutModel {
  name?: string;
  description?: string;
  comment?: string;
  value?: string;
  valueType?: string;
}

/**
 * @class
 * Initializes a new instance of the SwitchHistoryModel class.
 * @constructor
 * The switch history model.
 *
 * @member {number} [switchHistoryId] Gets or sets the switch history
 * identifier.
 * @member {number} [switchId] Gets or sets the switch identifier.
 * @member {number} [boardId] Gets or sets the board identifier.
 * @member {number} [createdUserId] Gets or sets the created user identifier.
 * @member {number} [modifiedUserId] Gets or sets the modified user identifier.
 * @member {string} [name] Gets or sets the name.
 * @member {string} [description] Gets or sets the description.
 * @member {string} [comment] Gets or sets the comment.
 * @member {date} [createdDate] Gets or sets the created date.
 * @member {date} [modifiedDate] Gets or sets the modified date.
 * @member {string} [value] Gets or sets the value.
 * @member {string} [valueType] Gets or sets the type of the value.
 * @member {string} [version] Gets or sets the version.
 */
export interface SwitchHistoryModel {
  switchHistoryId?: number;
  switchId?: number;
  boardId?: number;
  createdUserId?: number;
  modifiedUserId?: number;
  name?: string;
  description?: string;
  comment?: string;
  createdDate?: Date;
  modifiedDate?: Date;
  value?: string;
  valueType?: string;
  version?: string;
}

/**
 * @class
 * Initializes a new instance of the SwitchFilterModel class.
 * @constructor
 * The Switch Get Request Model.
 *
 * @member {string} [name] Gets or sets the name.
 * @member {string} [valueType] Gets or sets the type of the value.
 * @member {date} [createdDate] Gets or sets the created date.
 * @member {date} [modifiedDate] Gets or sets the modified date.
 */
export interface SwitchFilterModel {
  name?: string;
  valueType?: string;
  createdDate?: Date;
  modifiedDate?: Date;
}
