/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The Switch Get Request Model.
 *
 */
class SwitchFilterModel {
  /**
   * Create a SwitchFilterModel.
   * @member {string} [name] Gets or sets the name.
   * @member {string} [valueType] Gets or sets the type of the value.
   * @member {date} [createdDate] Gets or sets the created date.
   * @member {date} [modifiedDate] Gets or sets the modified date.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SwitchFilterModel
   *
   * @returns {object} metadata of SwitchFilterModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SwitchFilterModel',
      type: {
        name: 'Composite',
        className: 'SwitchFilterModel',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            constraints: {
              MaxLength: 50,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          valueType: {
            required: false,
            serializedName: 'valueType',
            constraints: {
              MaxLength: 50,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          },
          createdDate: {
            required: false,
            nullable: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          modifiedDate: {
            required: false,
            nullable: false,
            serializedName: 'modifiedDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = SwitchFilterModel;
