/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The switch history model.
 *
 */
class SwitchHistoryModel {
  /**
   * Create a SwitchHistoryModel.
   * @member {number} [switchHistoryId] Gets or sets the switch history
   * identifier.
   * @member {number} [switchId] Gets or sets the switch identifier.
   * @member {number} [boardId] Gets or sets the board identifier.
   * @member {number} [createdUserId] Gets or sets the created user identifier.
   * @member {number} [modifiedUserId] Gets or sets the modified user
   * identifier.
   * @member {string} [name] Gets or sets the name.
   * @member {string} [description] Gets or sets the description.
   * @member {string} [comment] Gets or sets the comment.
   * @member {date} [createdDate] Gets or sets the created date.
   * @member {date} [modifiedDate] Gets or sets the modified date.
   * @member {string} [value] Gets or sets the value.
   * @member {string} [valueType] Gets or sets the type of the value.
   * @member {string} [version] Gets or sets the version.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SwitchHistoryModel
   *
   * @returns {object} metadata of SwitchHistoryModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SwitchHistoryModel',
      type: {
        name: 'Composite',
        className: 'SwitchHistoryModel',
        modelProperties: {
          switchHistoryId: {
            required: false,
            nullable: false,
            serializedName: 'switchHistoryId',
            type: {
              name: 'Number'
            }
          },
          switchId: {
            required: false,
            nullable: false,
            serializedName: 'switchId',
            type: {
              name: 'Number'
            }
          },
          boardId: {
            required: false,
            nullable: false,
            serializedName: 'boardId',
            type: {
              name: 'Number'
            }
          },
          createdUserId: {
            required: false,
            nullable: false,
            serializedName: 'createdUserId',
            type: {
              name: 'Number'
            }
          },
          modifiedUserId: {
            required: false,
            nullable: false,
            serializedName: 'modifiedUserId',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          comment: {
            required: false,
            serializedName: 'comment',
            type: {
              name: 'String'
            }
          },
          createdDate: {
            required: false,
            nullable: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          },
          modifiedDate: {
            required: false,
            nullable: false,
            serializedName: 'modifiedDate',
            type: {
              name: 'DateTime'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          },
          valueType: {
            required: false,
            serializedName: 'valueType',
            type: {
              name: 'String'
            }
          },
          version: {
            required: false,
            serializedName: 'version',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SwitchHistoryModel;
