/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package swagger.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Switch Model.
 */
public class SwitchModel {
    /**
     * Gets or sets the switch identifier.
     */
    @JsonProperty(value = "switchId")
    private int switchId;

    /**
     * Gets or sets the board identifier.
     */
    @JsonProperty(value = "boardId")
    private int boardId;

    /**
     * Gets or sets the created user identifier.
     */
    @JsonProperty(value = "createdUserId")
    private int createdUserId;

    /**
     * Gets or sets the modified user identifier.
     */
    @JsonProperty(value = "modifiedUserId")
    private int modifiedUserId;

    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Gets or sets the description.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Gets or sets the comment.
     */
    @JsonProperty(value = "comment")
    private String comment;

    /**
     * Gets or sets the created date.
     */
    @JsonProperty(value = "createdDate")
    private DateTime createdDate;

    /**
     * Gets or sets the modified date.
     */
    @JsonProperty(value = "modifiedDate")
    private DateTime modifiedDate;

    /**
     * Gets or sets the value.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Gets or sets the type of the value.
     */
    @JsonProperty(value = "valueType")
    private String valueType;

    /**
     * Gets or sets the version.
     */
    @JsonProperty(value = "version")
    private String version;

    /**
     * Get gets or sets the switch identifier.
     *
     * @return the switchId value
     */
    public int switchId() {
        return this.switchId;
    }

    /**
     * Set gets or sets the switch identifier.
     *
     * @param switchId the switchId value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withSwitchId(int switchId) {
        this.switchId = switchId;
        return this;
    }

    /**
     * Get gets or sets the board identifier.
     *
     * @return the boardId value
     */
    public int boardId() {
        return this.boardId;
    }

    /**
     * Set gets or sets the board identifier.
     *
     * @param boardId the boardId value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withBoardId(int boardId) {
        this.boardId = boardId;
        return this;
    }

    /**
     * Get gets or sets the created user identifier.
     *
     * @return the createdUserId value
     */
    public int createdUserId() {
        return this.createdUserId;
    }

    /**
     * Set gets or sets the created user identifier.
     *
     * @param createdUserId the createdUserId value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withCreatedUserId(int createdUserId) {
        this.createdUserId = createdUserId;
        return this;
    }

    /**
     * Get gets or sets the modified user identifier.
     *
     * @return the modifiedUserId value
     */
    public int modifiedUserId() {
        return this.modifiedUserId;
    }

    /**
     * Set gets or sets the modified user identifier.
     *
     * @param modifiedUserId the modifiedUserId value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withModifiedUserId(int modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
        return this;
    }

    /**
     * Get gets or sets the name.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set gets or sets the name.
     *
     * @param name the name value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get gets or sets the description.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set gets or sets the description.
     *
     * @param description the description value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get gets or sets the comment.
     *
     * @return the comment value
     */
    public String comment() {
        return this.comment;
    }

    /**
     * Set gets or sets the comment.
     *
     * @param comment the comment value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withComment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get gets or sets the created date.
     *
     * @return the createdDate value
     */
    public DateTime createdDate() {
        return this.createdDate;
    }

    /**
     * Set gets or sets the created date.
     *
     * @param createdDate the createdDate value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get gets or sets the modified date.
     *
     * @return the modifiedDate value
     */
    public DateTime modifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Set gets or sets the modified date.
     *
     * @param modifiedDate the modifiedDate value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withModifiedDate(DateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
        return this;
    }

    /**
     * Get gets or sets the value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set gets or sets the value.
     *
     * @param value the value value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get gets or sets the type of the value.
     *
     * @return the valueType value
     */
    public String valueType() {
        return this.valueType;
    }

    /**
     * Set gets or sets the type of the value.
     *
     * @param valueType the valueType value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withValueType(String valueType) {
        this.valueType = valueType;
        return this;
    }

    /**
     * Get gets or sets the version.
     *
     * @return the version value
     */
    public String version() {
        return this.version;
    }

    /**
     * Set gets or sets the version.
     *
     * @param version the version value to set
     * @return the SwitchModel object itself.
     */
    public SwitchModel withVersion(String version) {
        this.version = version;
        return this;
    }

}
