/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package swagger.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Switch Get Request Model.
 */
public class SwitchFilterModel {
    /**
     * Gets or sets the name.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Gets or sets the type of the value.
     */
    @JsonProperty(value = "valueType")
    private String valueType;

    /**
     * Gets or sets the created date.
     */
    @JsonProperty(value = "createdDate")
    private DateTime createdDate;

    /**
     * Gets or sets the modified date.
     */
    @JsonProperty(value = "modifiedDate")
    private DateTime modifiedDate;

    /**
     * Get gets or sets the name.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set gets or sets the name.
     *
     * @param name the name value to set
     * @return the SwitchFilterModel object itself.
     */
    public SwitchFilterModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get gets or sets the type of the value.
     *
     * @return the valueType value
     */
    public String valueType() {
        return this.valueType;
    }

    /**
     * Set gets or sets the type of the value.
     *
     * @param valueType the valueType value to set
     * @return the SwitchFilterModel object itself.
     */
    public SwitchFilterModel withValueType(String valueType) {
        this.valueType = valueType;
        return this;
    }

    /**
     * Get gets or sets the created date.
     *
     * @return the createdDate value
     */
    public DateTime createdDate() {
        return this.createdDate;
    }

    /**
     * Set gets or sets the created date.
     *
     * @param createdDate the createdDate value to set
     * @return the SwitchFilterModel object itself.
     */
    public SwitchFilterModel withCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get gets or sets the modified date.
     *
     * @return the modifiedDate value
     */
    public DateTime modifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Set gets or sets the modified date.
     *
     * @param modifiedDate the modifiedDate value to set
     * @return the SwitchFilterModel object itself.
     */
    public SwitchFilterModel withModifiedDate(DateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
        return this;
    }

}
