// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.API.Switchboard.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The Board Get Request Model.
    /// </summary>
    public partial class BoardFilterModel
    {
        /// <summary>
        /// Initializes a new instance of the BoardFilterModel class.
        /// </summary>
        public BoardFilterModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BoardFilterModel class.
        /// </summary>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="createdDate">Gets or sets the created date.</param>
        /// <param name="modifiedDate">Gets or sets the modified date.</param>
        public BoardFilterModel(string name = default(string), System.DateTime createdDate = default(System.DateTime), System.DateTime modifiedDate = default(System.DateTime))
        {
            Name = name;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the created date.
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets the modified date.
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime ModifiedDate { get; set; }

    }
}
