// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.API.Switchboard.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The Board History Model.
    /// </summary>
    public partial class BoardHistoryModel
    {
        /// <summary>
        /// Initializes a new instance of the BoardHistoryModel class.
        /// </summary>
        public BoardHistoryModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BoardHistoryModel class.
        /// </summary>
        /// <param name="boardHistoryId">Gets or sets the board history
        /// identifier.</param>
        /// <param name="boardId">Gets or sets the board identifier.</param>
        /// <param name="accountId">Gets or sets the account
        /// identifier.</param>
        /// <param name="createdUserId">Gets or sets the created user
        /// identifier.</param>
        /// <param name="modifiedUserId">Gets or sets the modified user
        /// identifier.</param>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="description">Gets or sets the description.</param>
        /// <param name="createdDate">Gets or sets the created date.</param>
        /// <param name="modifiedDate">Gets or sets the modified date.</param>
        public BoardHistoryModel(int boardHistoryId = default(int), int boardId = default(int), int accountId = default(int), int createdUserId = default(int), int modifiedUserId = default(int), string name = default(string), string description = default(string), System.DateTime createdDate = default(System.DateTime), System.DateTime modifiedDate = default(System.DateTime))
        {
            BoardHistoryId = boardHistoryId;
            BoardId = boardId;
            AccountId = accountId;
            CreatedUserId = createdUserId;
            ModifiedUserId = modifiedUserId;
            Name = name;
            Description = description;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the board history identifier.
        /// </summary>
        [JsonProperty(PropertyName = "boardHistoryId")]
        public int BoardHistoryId { get; set; }

        /// <summary>
        /// Gets or sets the board identifier.
        /// </summary>
        [JsonProperty(PropertyName = "boardId")]
        public int BoardId { get; set; }

        /// <summary>
        /// Gets or sets the account identifier.
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public int AccountId { get; set; }

        /// <summary>
        /// Gets or sets the created user identifier.
        /// </summary>
        [JsonProperty(PropertyName = "createdUserId")]
        public int CreatedUserId { get; set; }

        /// <summary>
        /// Gets or sets the modified user identifier.
        /// </summary>
        [JsonProperty(PropertyName = "modifiedUserId")]
        public int ModifiedUserId { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the created date.
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets the modified date.
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime ModifiedDate { get; set; }

    }
}
