// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.API.Switchboard.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The Switch Get Request Model.
    /// </summary>
    public partial class SwitchFilterModel
    {
        /// <summary>
        /// Initializes a new instance of the SwitchFilterModel class.
        /// </summary>
        public SwitchFilterModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwitchFilterModel class.
        /// </summary>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="valueType">Gets or sets the type of the value.</param>
        /// <param name="createdDate">Gets or sets the created date.</param>
        /// <param name="modifiedDate">Gets or sets the modified date.</param>
        public SwitchFilterModel(string name = default(string), string valueType = default(string), System.DateTime createdDate = default(System.DateTime), System.DateTime modifiedDate = default(System.DateTime))
        {
            Name = name;
            ValueType = valueType;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the type of the value.
        /// </summary>
        [JsonProperty(PropertyName = "valueType")]
        public string ValueType { get; set; }

        /// <summary>
        /// Gets or sets the created date.
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets the modified date.
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name != null)
            {
                if (Name.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Name", 50);
                }
                if (Name.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Name", 0);
                }
            }
            if (ValueType != null)
            {
                if (ValueType.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ValueType", 50);
                }
                if (ValueType.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ValueType", 0);
                }
            }
        }
    }
}
