// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.API.Switchboard.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Switch Put Model.
    /// </summary>
    public partial class SwitchPutModel
    {
        /// <summary>
        /// Initializes a new instance of the SwitchPutModel class.
        /// </summary>
        public SwitchPutModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwitchPutModel class.
        /// </summary>
        /// <param name="name">Gets or sets the name.</param>
        /// <param name="description">Gets or sets the description.</param>
        /// <param name="comment">Gets or sets the comment.</param>
        /// <param name="value">Gets or sets the value.</param>
        /// <param name="valueType">Gets or sets the type of the value.</param>
        public SwitchPutModel(string name = default(string), string description = default(string), string comment = default(string), string value = default(string), string valueType = default(string))
        {
            Name = name;
            Description = description;
            Comment = comment;
            Value = value;
            ValueType = valueType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the comment.
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets the type of the value.
        /// </summary>
        [JsonProperty(PropertyName = "valueType")]
        public string ValueType { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name != null)
            {
                if (Name.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Name", 50);
                }
                if (Name.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Name", 0);
                }
            }
            if (Description != null)
            {
                if (Description.Length > 250)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Description", 250);
                }
                if (Description.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Description", 0);
                }
            }
            if (Comment != null)
            {
                if (Comment.Length > 250)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Comment", 250);
                }
                if (Comment.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Comment", 0);
                }
            }
            if (ValueType != null)
            {
                if (ValueType.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ValueType", 10);
                }
                if (ValueType.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ValueType", 0);
                }
            }
        }
    }
}
