/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";


/**
 * @interface
 * An interface representing BoardModel.
 * The board model.
 *
 */
export interface BoardModel {
  /**
   * @member {number} [boardId] Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * @member {number} [accountId] Gets or sets the account identifier.
   */
  accountId?: number;
  /**
   * @member {number} [createdUserId] Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * @member {number} [modifiedUserId] Gets or sets the modified user
   * identifier.
   */
  modifiedUserId?: number;
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {Date} [createdDate] Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * @member {Date} [modifiedDate] Gets or sets the modified date.
   */
  modifiedDate?: Date;
}

/**
 * @interface
 * An interface representing BoardPutModel.
 * The board put model.
 *
 */
export interface BoardPutModel {
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
}

/**
 * @interface
 * An interface representing BoardPostModel.
 * The board post model.
 *
 */
export interface BoardPostModel {
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
}

/**
 * @interface
 * An interface representing BoardHistoryModel.
 * The Board History Model.
 *
 */
export interface BoardHistoryModel {
  /**
   * @member {number} [boardHistoryId] Gets or sets the board history
   * identifier.
   */
  boardHistoryId?: number;
  /**
   * @member {number} [boardId] Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * @member {number} [accountId] Gets or sets the account identifier.
   */
  accountId?: number;
  /**
   * @member {number} [createdUserId] Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * @member {number} [modifiedUserId] Gets or sets the modified user
   * identifier.
   */
  modifiedUserId?: number;
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {Date} [createdDate] Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * @member {Date} [modifiedDate] Gets or sets the modified date.
   */
  modifiedDate?: Date;
}

/**
 * @interface
 * An interface representing BoardFilterModel.
 * The Board Get Request Model.
 *
 */
export interface BoardFilterModel {
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {Date} [createdDate] Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * @member {Date} [modifiedDate] Gets or sets the modified date.
   */
  modifiedDate?: Date;
}

/**
 * @interface
 * An interface representing SwitchModel.
 * Switch Model.
 *
 */
export interface SwitchModel {
  /**
   * @member {number} [switchId] Gets or sets the switch identifier.
   */
  switchId?: number;
  /**
   * @member {number} [boardId] Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * @member {number} [createdUserId] Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * @member {number} [modifiedUserId] Gets or sets the modified user
   * identifier.
   */
  modifiedUserId?: number;
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {string} [comment] Gets or sets the comment.
   */
  comment?: string;
  /**
   * @member {Date} [createdDate] Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * @member {Date} [modifiedDate] Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * @member {string} [value] Gets or sets the value.
   */
  value?: string;
  /**
   * @member {string} [valueType] Gets or sets the type of the value.
   */
  valueType?: string;
  /**
   * @member {string} [version] Gets or sets the version.
   */
  version?: string;
}

/**
 * @interface
 * An interface representing SwitchPostModel.
 * Switch Post Model.
 *
 */
export interface SwitchPostModel {
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {string} [comment] Gets or sets the comment.
   */
  comment?: string;
  /**
   * @member {string} [value] Gets or sets the value.
   */
  value?: string;
  /**
   * @member {string} [valueType] Gets or sets the type of the value.
   */
  valueType?: string;
}

/**
 * @interface
 * An interface representing SwitchPutModel.
 * Switch Put Model.
 *
 */
export interface SwitchPutModel {
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {string} [comment] Gets or sets the comment.
   */
  comment?: string;
  /**
   * @member {string} [value] Gets or sets the value.
   */
  value?: string;
  /**
   * @member {string} [valueType] Gets or sets the type of the value.
   */
  valueType?: string;
}

/**
 * @interface
 * An interface representing SwitchHistoryModel.
 * The switch history model.
 *
 */
export interface SwitchHistoryModel {
  /**
   * @member {number} [switchHistoryId] Gets or sets the switch history
   * identifier.
   */
  switchHistoryId?: number;
  /**
   * @member {number} [switchId] Gets or sets the switch identifier.
   */
  switchId?: number;
  /**
   * @member {number} [boardId] Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * @member {number} [createdUserId] Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * @member {number} [modifiedUserId] Gets or sets the modified user
   * identifier.
   */
  modifiedUserId?: number;
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [description] Gets or sets the description.
   */
  description?: string;
  /**
   * @member {string} [comment] Gets or sets the comment.
   */
  comment?: string;
  /**
   * @member {Date} [createdDate] Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * @member {Date} [modifiedDate] Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * @member {string} [value] Gets or sets the value.
   */
  value?: string;
  /**
   * @member {string} [valueType] Gets or sets the type of the value.
   */
  valueType?: string;
  /**
   * @member {string} [version] Gets or sets the version.
   */
  version?: string;
}

/**
 * @interface
 * An interface representing SwitchFilterModel.
 * The Switch Get Request Model.
 *
 */
export interface SwitchFilterModel {
  /**
   * @member {string} [name] Gets or sets the name.
   */
  name?: string;
  /**
   * @member {string} [valueType] Gets or sets the type of the value.
   */
  valueType?: string;
  /**
   * @member {Date} [createdDate] Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * @member {Date} [modifiedDate] Gets or sets the modified date.
   */
  modifiedDate?: Date;
}

/**
 * @interface
 * An interface representing SoftheonSwitchboardUpdateBoardOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface SoftheonSwitchboardUpdateBoardOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {BoardPutModel} [model] The model.
   */
  model?: BoardPutModel;
}

/**
 * @interface
 * An interface representing SoftheonSwitchboardCreateBoardOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface SoftheonSwitchboardCreateBoardOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {BoardPostModel} [model] The model.
   */
  model?: BoardPostModel;
}

/**
 * @interface
 * An interface representing SoftheonSwitchboardGetBoardsByFilterOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface SoftheonSwitchboardGetBoardsByFilterOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {BoardFilterModel} [model] The model.
   */
  model?: BoardFilterModel;
}

/**
 * @interface
 * An interface representing SoftheonSwitchboardCreateSwitchOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface SoftheonSwitchboardCreateSwitchOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {SwitchPostModel} [switchPostModel] The switch model.
   */
  switchPostModel?: SwitchPostModel;
}

/**
 * @interface
 * An interface representing SoftheonSwitchboardUpdateSwitchOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface SoftheonSwitchboardUpdateSwitchOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {SwitchPutModel} [switchPutModel] The switch model.
   */
  switchPutModel?: SwitchPutModel;
}

/**
 * @interface
 * An interface representing SoftheonSwitchboardGetSwitchesByFilterOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface SoftheonSwitchboardGetSwitchesByFilterOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {SwitchFilterModel} [model] The model.
   */
  model?: SwitchFilterModel;
}

/**
 * Contains response data for the getBoardById operation.
 */
export type GetBoardByIdResponse = {
  /**
   * Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * Gets or sets the account identifier.
   */
  accountId?: number;
  /**
   * Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * Gets or sets the modified user identifier.
   */
  modifiedUserId?: number;
  /**
   * Gets or sets the name.
   */
  name?: string;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BoardModel;
    };
};

/**
 * Contains response data for the getAllBoards operation.
 */
export type GetAllBoardsResponse = Array<BoardModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BoardModel[];
    };
};

/**
 * Contains response data for the createBoard operation.
 */
export type CreateBoardResponse = {
  /**
   * Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * Gets or sets the account identifier.
   */
  accountId?: number;
  /**
   * Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * Gets or sets the modified user identifier.
   */
  modifiedUserId?: number;
  /**
   * Gets or sets the name.
   */
  name?: string;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BoardModel;
    };
};

/**
 * Contains response data for the getAllBoardHistoryForTheAccount operation.
 */
export type GetAllBoardHistoryForTheAccountResponse = Array<BoardHistoryModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BoardHistoryModel[];
    };
};

/**
 * Contains response data for the getBoardHistoryById operation.
 */
export type GetBoardHistoryByIdResponse = {
  /**
   * Gets or sets the board history identifier.
   */
  boardHistoryId?: number;
  /**
   * Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * Gets or sets the account identifier.
   */
  accountId?: number;
  /**
   * Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * Gets or sets the modified user identifier.
   */
  modifiedUserId?: number;
  /**
   * Gets or sets the name.
   */
  name?: string;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BoardHistoryModel;
    };
};

/**
 * Contains response data for the getBoardsByFilter operation.
 */
export type GetBoardsByFilterResponse = Array<BoardModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BoardModel[];
    };
};

/**
 * Contains response data for the getSwitchesByBoardId operation.
 */
export type GetSwitchesByBoardIdResponse = Array<SwitchModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchModel[];
    };
};

/**
 * Contains response data for the createSwitch operation.
 */
export type CreateSwitchResponse = {
  /**
   * Gets or sets the switch identifier.
   */
  switchId?: number;
  /**
   * Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * Gets or sets the modified user identifier.
   */
  modifiedUserId?: number;
  /**
   * Gets or sets the name.
   */
  name?: string;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the comment.
   */
  comment?: string;
  /**
   * Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * Gets or sets the value.
   */
  value?: string;
  /**
   * Gets or sets the type of the value.
   */
  valueType?: string;
  /**
   * Gets or sets the version.
   */
  version?: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchModel;
    };
};

/**
 * Contains response data for the getSwitch operation.
 */
export type GetSwitchResponse = {
  /**
   * Gets or sets the switch identifier.
   */
  switchId?: number;
  /**
   * Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * Gets or sets the modified user identifier.
   */
  modifiedUserId?: number;
  /**
   * Gets or sets the name.
   */
  name?: string;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the comment.
   */
  comment?: string;
  /**
   * Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * Gets or sets the value.
   */
  value?: string;
  /**
   * Gets or sets the type of the value.
   */
  valueType?: string;
  /**
   * Gets or sets the version.
   */
  version?: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchModel;
    };
};

/**
 * Contains response data for the getSwitchHistory operation.
 */
export type GetSwitchHistoryResponse = {
  /**
   * Gets or sets the switch history identifier.
   */
  switchHistoryId?: number;
  /**
   * Gets or sets the switch identifier.
   */
  switchId?: number;
  /**
   * Gets or sets the board identifier.
   */
  boardId?: number;
  /**
   * Gets or sets the created user identifier.
   */
  createdUserId?: number;
  /**
   * Gets or sets the modified user identifier.
   */
  modifiedUserId?: number;
  /**
   * Gets or sets the name.
   */
  name?: string;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets the comment.
   */
  comment?: string;
  /**
   * Gets or sets the created date.
   */
  createdDate?: Date;
  /**
   * Gets or sets the modified date.
   */
  modifiedDate?: Date;
  /**
   * Gets or sets the value.
   */
  value?: string;
  /**
   * Gets or sets the type of the value.
   */
  valueType?: string;
  /**
   * Gets or sets the version.
   */
  version?: string;
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchHistoryModel;
    };
};

/**
 * Contains response data for the getAllSwitchHistoryByBoard operation.
 */
export type GetAllSwitchHistoryByBoardResponse = Array<SwitchHistoryModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchHistoryModel[];
    };
};

/**
 * Contains response data for the getAllSwitchHistoryBySwitch operation.
 */
export type GetAllSwitchHistoryBySwitchResponse = Array<SwitchHistoryModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchHistoryModel[];
    };
};

/**
 * Contains response data for the getSwitchesByFilter operation.
 */
export type GetSwitchesByFilterResponse = Array<SwitchModel> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: SwitchModel[];
    };
};
