/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";


export const BoardModel: msRest.CompositeMapper = {
  serializedName: "BoardModel",
  type: {
    name: "Composite",
    className: "BoardModel",
    modelProperties: {
      boardId: {
        nullable: false,
        serializedName: "boardId",
        type: {
          name: "Number"
        }
      },
      accountId: {
        nullable: false,
        serializedName: "accountId",
        type: {
          name: "Number"
        }
      },
      createdUserId: {
        nullable: false,
        serializedName: "createdUserId",
        type: {
          name: "Number"
        }
      },
      modifiedUserId: {
        nullable: false,
        serializedName: "modifiedUserId",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      createdDate: {
        nullable: false,
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        nullable: false,
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      },
      createdUserName: {
        serializedName: "createdUserName",
        type: {
          name: "String"
        }
      },
      modifiedUserName: {
        serializedName: "modifiedUserName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BoardPutModel: msRest.CompositeMapper = {
  serializedName: "BoardPutModel",
  type: {
    name: "Composite",
    className: "BoardPutModel",
    modelProperties: {
      name: {
        serializedName: "name",
        constraints: {
          MaxLength: 50,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        constraints: {
          MaxLength: 250,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BoardPostModel: msRest.CompositeMapper = {
  serializedName: "BoardPostModel",
  type: {
    name: "Composite",
    className: "BoardPostModel",
    modelProperties: {
      name: {
        required: true,
        serializedName: "name",
        constraints: {
          MaxLength: 50,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        constraints: {
          MaxLength: 250,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BoardHistoryModel: msRest.CompositeMapper = {
  serializedName: "BoardHistoryModel",
  type: {
    name: "Composite",
    className: "BoardHistoryModel",
    modelProperties: {
      boardHistoryId: {
        nullable: false,
        serializedName: "boardHistoryId",
        type: {
          name: "Number"
        }
      },
      boardId: {
        nullable: false,
        serializedName: "boardId",
        type: {
          name: "Number"
        }
      },
      accountId: {
        nullable: false,
        serializedName: "accountId",
        type: {
          name: "Number"
        }
      },
      createdUserId: {
        nullable: false,
        serializedName: "createdUserId",
        type: {
          name: "Number"
        }
      },
      modifiedUserId: {
        nullable: false,
        serializedName: "modifiedUserId",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      createdDate: {
        nullable: false,
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        nullable: false,
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      },
      createdUserName: {
        serializedName: "createdUserName",
        type: {
          name: "String"
        }
      },
      modifiedUserName: {
        serializedName: "modifiedUserName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TaskBoardModel: msRest.CompositeMapper = {
  serializedName: "TaskBoardModel",
  type: {
    name: "Composite",
    className: "TaskBoardModel",
    modelProperties: {
      taskId: {
        nullable: false,
        serializedName: "taskId",
        type: {
          name: "Number"
        }
      },
      boardId: {
        nullable: false,
        serializedName: "boardId",
        type: {
          name: "Number"
        }
      },
      startDate: {
        nullable: false,
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const TaskBoardPostModel: msRest.CompositeMapper = {
  serializedName: "TaskBoardPostModel",
  type: {
    name: "Composite",
    className: "TaskBoardPostModel",
    modelProperties: {
      startDate: {
        nullable: false,
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const TaskBoardPutModel: msRest.CompositeMapper = {
  serializedName: "TaskBoardPutModel",
  type: {
    name: "Composite",
    className: "TaskBoardPutModel",
    modelProperties: {
      startDate: {
        nullable: false,
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const BoardFilterModel: msRest.CompositeMapper = {
  serializedName: "BoardFilterModel",
  type: {
    name: "Composite",
    className: "BoardFilterModel",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      createdDate: {
        nullable: false,
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        nullable: false,
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const SwitchModel: msRest.CompositeMapper = {
  serializedName: "SwitchModel",
  type: {
    name: "Composite",
    className: "SwitchModel",
    modelProperties: {
      switchId: {
        nullable: false,
        serializedName: "switchId",
        type: {
          name: "Number"
        }
      },
      boardId: {
        nullable: false,
        serializedName: "boardId",
        type: {
          name: "Number"
        }
      },
      createdUserId: {
        nullable: false,
        serializedName: "createdUserId",
        type: {
          name: "Number"
        }
      },
      modifiedUserId: {
        nullable: false,
        serializedName: "modifiedUserId",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      comment: {
        serializedName: "comment",
        type: {
          name: "String"
        }
      },
      createdDate: {
        nullable: false,
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        nullable: false,
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      valueType: {
        serializedName: "valueType",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      createdUserName: {
        serializedName: "createdUserName",
        type: {
          name: "String"
        }
      },
      modifiedUserName: {
        serializedName: "modifiedUserName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SwitchPostModel: msRest.CompositeMapper = {
  serializedName: "SwitchPostModel",
  type: {
    name: "Composite",
    className: "SwitchPostModel",
    modelProperties: {
      name: {
        required: true,
        serializedName: "name",
        constraints: {
          MaxLength: 50,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        constraints: {
          MaxLength: 250,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      comment: {
        serializedName: "comment",
        constraints: {
          MaxLength: 250,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      value: {
        required: true,
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      valueType: {
        required: true,
        serializedName: "valueType",
        constraints: {
          MaxLength: 10,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SwitchPutModel: msRest.CompositeMapper = {
  serializedName: "SwitchPutModel",
  type: {
    name: "Composite",
    className: "SwitchPutModel",
    modelProperties: {
      name: {
        serializedName: "name",
        constraints: {
          MaxLength: 50,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        constraints: {
          MaxLength: 250,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      comment: {
        serializedName: "comment",
        constraints: {
          MaxLength: 250,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      valueType: {
        serializedName: "valueType",
        constraints: {
          MaxLength: 10,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SwitchHistoryModel: msRest.CompositeMapper = {
  serializedName: "SwitchHistoryModel",
  type: {
    name: "Composite",
    className: "SwitchHistoryModel",
    modelProperties: {
      switchHistoryId: {
        nullable: false,
        serializedName: "switchHistoryId",
        type: {
          name: "Number"
        }
      },
      switchId: {
        nullable: false,
        serializedName: "switchId",
        type: {
          name: "Number"
        }
      },
      boardId: {
        nullable: false,
        serializedName: "boardId",
        type: {
          name: "Number"
        }
      },
      createdUserId: {
        nullable: false,
        serializedName: "createdUserId",
        type: {
          name: "Number"
        }
      },
      modifiedUserId: {
        nullable: false,
        serializedName: "modifiedUserId",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      comment: {
        serializedName: "comment",
        type: {
          name: "String"
        }
      },
      createdDate: {
        nullable: false,
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        nullable: false,
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      valueType: {
        serializedName: "valueType",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      },
      createdUserName: {
        serializedName: "createdUserName",
        type: {
          name: "String"
        }
      },
      modifiedUserName: {
        serializedName: "modifiedUserName",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const TaskSwitchModel: msRest.CompositeMapper = {
  serializedName: "TaskSwitchModel",
  type: {
    name: "Composite",
    className: "TaskSwitchModel",
    modelProperties: {
      taskId: {
        nullable: false,
        serializedName: "taskId",
        type: {
          name: "Number"
        }
      },
      switchId: {
        nullable: false,
        serializedName: "switchId",
        type: {
          name: "Number"
        }
      },
      startDate: {
        nullable: false,
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const TaskSwitchPostModel: msRest.CompositeMapper = {
  serializedName: "TaskSwitchPostModel",
  type: {
    name: "Composite",
    className: "TaskSwitchPostModel",
    modelProperties: {
      startDate: {
        nullable: false,
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const TaskSwitchPutModel: msRest.CompositeMapper = {
  serializedName: "TaskSwitchPutModel",
  type: {
    name: "Composite",
    className: "TaskSwitchPutModel",
    modelProperties: {
      startDate: {
        nullable: false,
        serializedName: "startDate",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const SwitchFilterModel: msRest.CompositeMapper = {
  serializedName: "SwitchFilterModel",
  type: {
    name: "Composite",
    className: "SwitchFilterModel",
    modelProperties: {
      name: {
        serializedName: "name",
        constraints: {
          MaxLength: 50,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      valueType: {
        serializedName: "valueType",
        constraints: {
          MaxLength: 50,
          MinLength: 0
        },
        type: {
          name: "String"
        }
      },
      createdDate: {
        nullable: false,
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        nullable: false,
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};
