/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";

export const accountId: msRest.OperationURLParameter = {
  parameterPath: "accountId",
  mapper: {
    required: true,
    serializedName: "accountId",
    type: {
      name: "Number"
    }
  }
};
export const boardId: msRest.OperationURLParameter = {
  parameterPath: "boardId",
  mapper: {
    required: true,
    serializedName: "boardId",
    type: {
      name: "Number"
    }
  }
};
export const boardName: msRest.OperationURLParameter = {
  parameterPath: "boardName",
  mapper: {
    required: true,
    serializedName: "boardName",
    type: {
      name: "String"
    }
  }
};
export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "Number"
    }
  }
};
export const switchHistoryId: msRest.OperationURLParameter = {
  parameterPath: "switchHistoryId",
  mapper: {
    required: true,
    serializedName: "switchHistoryId",
    type: {
      name: "Number"
    }
  }
};
export const switchId: msRest.OperationURLParameter = {
  parameterPath: "switchId",
  mapper: {
    required: true,
    serializedName: "switchId",
    type: {
      name: "Number"
    }
  }
};
export const switchName: msRest.OperationURLParameter = {
  parameterPath: "switchName",
  mapper: {
    required: true,
    serializedName: "switchName",
    type: {
      name: "String"
    }
  }
};
export const taskId: msRest.OperationURLParameter = {
  parameterPath: "taskId",
  mapper: {
    required: true,
    serializedName: "taskId",
    type: {
      name: "Number"
    }
  }
};
