# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Swagger
  module Models
    #
    # The board model.
    #
    class BoardModel
      # @return [Integer] Gets or sets the board identifier.
      attr_accessor :board_id

      # @return [Integer] Gets or sets the account identifier.
      attr_accessor :account_id

      # @return [Integer] Gets or sets the created user identifier.
      attr_accessor :created_user_id

      # @return [Integer] Gets or sets the modified user identifier.
      attr_accessor :modified_user_id

      # @return [String] Gets or sets the name.
      attr_accessor :name

      # @return [String] Gets or sets the description.
      attr_accessor :description

      # @return [DateTime] Gets or sets the created date.
      attr_accessor :created_date

      # @return [DateTime] Gets or sets the modified date.
      attr_accessor :modified_date


      #
      # Mapper for BoardModel class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'BoardModel',
          type: {
            name: 'Composite',
            class_name: 'BoardModel',
            model_properties: {
              board_id: {
                client_side_validation: true,
                required: false,
                serialized_name: 'boardId',
                type: {
                  name: 'Number'
                }
              },
              account_id: {
                client_side_validation: true,
                required: false,
                serialized_name: 'accountId',
                type: {
                  name: 'Number'
                }
              },
              created_user_id: {
                client_side_validation: true,
                required: false,
                serialized_name: 'createdUserId',
                type: {
                  name: 'Number'
                }
              },
              modified_user_id: {
                client_side_validation: true,
                required: false,
                serialized_name: 'modifiedUserId',
                type: {
                  name: 'Number'
                }
              },
              name: {
                client_side_validation: true,
                required: false,
                serialized_name: 'name',
                type: {
                  name: 'String'
                }
              },
              description: {
                client_side_validation: true,
                required: false,
                serialized_name: 'description',
                type: {
                  name: 'String'
                }
              },
              created_date: {
                client_side_validation: true,
                required: false,
                serialized_name: 'createdDate',
                type: {
                  name: 'DateTime'
                }
              },
              modified_date: {
                client_side_validation: true,
                required: false,
                serialized_name: 'modifiedDate',
                type: {
                  name: 'DateTime'
                }
              }
            }
          }
        }
      end
    end
  end
end
