# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Swagger
  module Models
    #
    # The Switch Get Request Model.
    #
    class SwitchFilterModel
      # @return [String] Gets or sets the name.
      attr_accessor :name

      # @return [String] Gets or sets the type of the value.
      attr_accessor :value_type

      # @return [DateTime] Gets or sets the created date.
      attr_accessor :created_date

      # @return [DateTime] Gets or sets the modified date.
      attr_accessor :modified_date


      #
      # Mapper for SwitchFilterModel class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'SwitchFilterModel',
          type: {
            name: 'Composite',
            class_name: 'SwitchFilterModel',
            model_properties: {
              name: {
                client_side_validation: true,
                required: false,
                serialized_name: 'name',
                constraints: {
                  MaxLength: 50,
                  MinLength: 0
                },
                type: {
                  name: 'String'
                }
              },
              value_type: {
                client_side_validation: true,
                required: false,
                serialized_name: 'valueType',
                constraints: {
                  MaxLength: 50,
                  MinLength: 0
                },
                type: {
                  name: 'String'
                }
              },
              created_date: {
                client_side_validation: true,
                required: false,
                serialized_name: 'createdDate',
                type: {
                  name: 'DateTime'
                }
              },
              modified_date: {
                client_side_validation: true,
                required: false,
                serialized_name: 'modifiedDate',
                type: {
                  name: 'DateTime'
                }
              }
            }
          }
        }
      end
    end
  end
end
