# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Swagger
  module Models
    #
    # Switch Post Model.
    #
    class SwitchPostModel
      # @return [String] Gets or sets the name.
      attr_accessor :name

      # @return [String] Gets or sets the description.
      attr_accessor :description

      # @return [String] Gets or sets the comment.
      attr_accessor :comment

      # @return [String] Gets or sets the value.
      attr_accessor :value

      # @return [String] Gets or sets the type of the value.
      attr_accessor :value_type


      #
      # Mapper for SwitchPostModel class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'SwitchPostModel',
          type: {
            name: 'Composite',
            class_name: 'SwitchPostModel',
            model_properties: {
              name: {
                client_side_validation: true,
                required: false,
                serialized_name: 'name',
                constraints: {
                  MaxLength: 50,
                  MinLength: 0
                },
                type: {
                  name: 'String'
                }
              },
              description: {
                client_side_validation: true,
                required: false,
                serialized_name: 'description',
                constraints: {
                  MaxLength: 250,
                  MinLength: 0
                },
                type: {
                  name: 'String'
                }
              },
              comment: {
                client_side_validation: true,
                required: false,
                serialized_name: 'comment',
                constraints: {
                  MaxLength: 250,
                  MinLength: 0
                },
                type: {
                  name: 'String'
                }
              },
              value: {
                client_side_validation: true,
                required: false,
                serialized_name: 'value',
                type: {
                  name: 'String'
                }
              },
              value_type: {
                client_side_validation: true,
                required: false,
                serialized_name: 'valueType',
                constraints: {
                  MaxLength: 10,
                  MinLength: 0
                },
                type: {
                  name: 'String'
                }
              }
            }
          }
        }
      end
    end
  end
end
