# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .softheon_switchboard import SoftheonSwitchboard
from .version import VERSION

__all__ = ['SoftheonSwitchboard']

__version__ = VERSION

