# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BoardFilterModel(Model):
    """The Board Get Request Model.

    :param name: Gets or sets the name.
    :type name: str
    :param created_date: Gets or sets the created date.
    :type created_date: datetime
    :param modified_date: Gets or sets the modified date.
    :type modified_date: datetime
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'modified_date': {'key': 'modifiedDate', 'type': 'iso-8601'},
    }

    def __init__(self, name=None, created_date=None, modified_date=None):
        super(BoardFilterModel, self).__init__()
        self.name = name
        self.created_date = created_date
        self.modified_date = modified_date
