# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BoardHistoryModel(Model):
    """The Board History Model.

    :param board_history_id: Gets or sets the board history identifier.
    :type board_history_id: int
    :param board_id: Gets or sets the board identifier.
    :type board_id: int
    :param account_id: Gets or sets the account identifier.
    :type account_id: int
    :param created_user_id: Gets or sets the created user identifier.
    :type created_user_id: int
    :param modified_user_id: Gets or sets the modified user identifier.
    :type modified_user_id: int
    :param name: Gets or sets the name.
    :type name: str
    :param description: Gets or sets the description.
    :type description: str
    :param created_date: Gets or sets the created date.
    :type created_date: datetime
    :param modified_date: Gets or sets the modified date.
    :type modified_date: datetime
    """

    _attribute_map = {
        'board_history_id': {'key': 'boardHistoryId', 'type': 'int'},
        'board_id': {'key': 'boardId', 'type': 'int'},
        'account_id': {'key': 'accountId', 'type': 'int'},
        'created_user_id': {'key': 'createdUserId', 'type': 'int'},
        'modified_user_id': {'key': 'modifiedUserId', 'type': 'int'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'modified_date': {'key': 'modifiedDate', 'type': 'iso-8601'},
    }

    def __init__(self, board_history_id=None, board_id=None, account_id=None, created_user_id=None, modified_user_id=None, name=None, description=None, created_date=None, modified_date=None):
        super(BoardHistoryModel, self).__init__()
        self.board_history_id = board_history_id
        self.board_id = board_id
        self.account_id = account_id
        self.created_user_id = created_user_id
        self.modified_user_id = modified_user_id
        self.name = name
        self.description = description
        self.created_date = created_date
        self.modified_date = modified_date
