# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SwitchFilterModel(Model):
    """The Switch Get Request Model.

    :param name: Gets or sets the name.
    :type name: str
    :param value_type: Gets or sets the type of the value.
    :type value_type: str
    :param created_date: Gets or sets the created date.
    :type created_date: datetime
    :param modified_date: Gets or sets the modified date.
    :type modified_date: datetime
    """

    _validation = {
        'name': {'max_length': 50, 'min_length': 0},
        'value_type': {'max_length': 50, 'min_length': 0},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'value_type': {'key': 'valueType', 'type': 'str'},
        'created_date': {'key': 'createdDate', 'type': 'iso-8601'},
        'modified_date': {'key': 'modifiedDate', 'type': 'iso-8601'},
    }

    def __init__(self, name=None, value_type=None, created_date=None, modified_date=None):
        super(SwitchFilterModel, self).__init__()
        self.name = name
        self.value_type = value_type
        self.created_date = created_date
        self.modified_date = modified_date
